import { prisma } from './prisma.js';
import { sendEmail, generateEmailHtml } from './email.js';
import { createNotification } from './notifications.js';
import { formatCents } from './money.js';

const INTERVAL_MS = 24 * 60 * 60 * 1000; // 24 hours
// Held back until the server is up. This is the heaviest thing that used to run
// at boot — it generates invoices, writes notifications and sends reminder
// email — and it ran before app.listen(), delaying the first health response.
// A daily job does not care about the first minute of uptime.
const STARTUP_DELAY_MS = 60 * 1000;

export function startSubscriptionBillingJob(): void {
  // runBillingCycle() swallows its own errors, but it is called here as a
  // floating promise: anything that ever escapes it would reach the
  // unhandledRejection handler in index.ts, which shuts the whole API down.
  const safeRun = () =>
    runBillingCycle().catch(error =>
      console.error('❌ [SubscriptionBilling] Error running billing cycle:', error)
    );

  setTimeout(safeRun, STARTUP_DELAY_MS);
  setInterval(safeRun, INTERVAL_MS);
  console.log('🔄 [SubscriptionBilling] Daily billing job started.');
}

export async function runBillingCycle(): Promise<void> {
  console.log('🔄 [SubscriptionBilling] Running billing cycle...');
  try {
    const now = new Date();
    const currentDay = now.getDate();
    const currentYear = now.getFullYear();
    const currentMonth = now.getMonth(); // 0-indexed

    // 1. Generate Monthly Invoices for Active Subscriptions
    const activeSubscriptions = await prisma.subscription.findMany({
      where: { status: 'ACTIVE' },
      include: {
        client: true,
      },
    });

    const settings = await prisma.agencySettings.findFirst();
    const taxRate = settings?.taxRate ?? 0;

    for (const sub of activeSubscriptions) {
      const client = sub.client;
      // If invoiceGenerationDay is null/undefined, default to 1st of the month
      const targetDay = client.invoiceGenerationDay ?? 1;

      // If today is the generation day for this client
      if (currentDay === targetDay) {
        // Check if an invoice has already been generated for this subscription in the current calendar month
        const startOfMonth = new Date(currentYear, currentMonth, 1);
        const endOfMonth = new Date(currentYear, currentMonth + 1, 0, 23, 59, 59, 999);

        const existingInvoice = await prisma.invoice.findFirst({
          where: {
            subscriptionId: sub.id,
            date: {
              gte: startOfMonth,
              lte: endOfMonth,
            },
          },
        });

        if (!existingInvoice) {
          console.log(`Generating monthly invoice for subscription ${sub.id} (Client: ${client.name})`);

          // Generate unique short invoice number
          let invoiceNumber = '';
          while (true) {
            const num = Math.floor(Math.random() * 9000 + 1000);
            invoiceNumber = `INV-${num}`;
            const existing = await prisma.invoice.findUnique({
              where: { invoiceNumber }
            });
            if (!existing) {
              break;
            }
          }

          // Compute amount with tax
          const subtotal = sub.amount; // in cents
          const totalAmount = subtotal + Math.round(subtotal * (taxRate / 100));

          // Set due date to 14 days from now
          const dueDate = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);

          await prisma.invoice.create({
            data: {
              invoiceNumber,
              clientId: sub.clientId,
              subscriptionId: sub.id,
              autoGenerated: true,
              amount: totalAmount,
              status: 'PENDING',
              date: now,
              dueDate,
              taxRate,
              notes: settings?.defaultInvoiceNotes || "Thank you for your business! Please make payment within 14 days.",
              items: {
                create: [
                  {
                    description: `Monthly subscription - ${sub.plan}`,
                    quantity: 1,
                    unitPrice: sub.amount,
                    position: 0,
                  },
                ],
              },
            },
          });
          createNotification({
            title: 'Auto-Invoice Generated',
            message: `Invoice ${invoiceNumber} generated for ${client.company || client.name} (${sub.plan}).`,
            type: 'INVOICE_AUTO_GENERATED',
            category: 'INFORMATION',
            entityType: 'INVOICE',
            entityId: invoiceNumber,
            actionUrl: `/dashboard/invoices/view/${invoiceNumber}`,
          });
          console.log(`Successfully generated invoice ${invoiceNumber} for client ${client.name}`);
        }
      }
    }

    // 2–3. Payment reminders and overdue notices. Clients switched to "send
    // automatically" get them now; everyone else waits in the approval list on
    // the Invoices page, because unpaid can mean the work isn't finished yet.
    const due = await findDueReminders(now);
    const waiting = due.filter(d => !d.invoice.client.autoSendReminders);
    for (const d of due) {
      if (d.invoice.client.autoSendReminders) await sendDueReminder(d, now);
    }
    if (waiting.length > 0) {
      createNotification({
        title: 'Reminder emails need your approval',
        message: `${waiting.length} payment reminder email${waiting.length === 1 ? ' is' : 's are'} waiting. Nothing is sent to these clients until you approve.`,
        type: 'INVOICE_REMINDERS_PENDING',
        category: 'ACTION_REQUIRED',
        actionUrl: '/dashboard/invoices',
      });
    }

    // 4. Warning: Invoices due in 3 days (deduplicated — only fire once per invoice)
    const threeDaysFromNow = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);
    const dueSoonInvoices = await prisma.invoice.findMany({
      where: {
        status: 'PENDING',
        dueDate: {
          gte: now,
          lte: threeDaysFromNow,
        },
        dueSoonNotifiedAt: null,
      },
      include: { client: true },
    });

    for (const inv of dueSoonInvoices) {
      const client = inv.client;
      const daysLeft = Math.ceil((inv.dueDate.getTime() - now.getTime()) / (24 * 60 * 60 * 1000));
      createNotification({
        title: 'Invoice Due Soon 🔔',
        message: `Invoice ${inv.invoiceNumber} for ${client.company || client.name} is due in ${daysLeft} day${daysLeft === 1 ? '' : 's'}.`,
        type: 'INVOICE_DUE_SOON',
        category: 'WARNING',
        entityType: 'INVOICE',
        entityId: inv.invoiceNumber || inv.id,
        actionUrl: `/dashboard/invoices/view/${inv.invoiceNumber || inv.id}`,
      });
      await prisma.invoice.update({
        where: { id: inv.id },
        data: { dueSoonNotifiedAt: now } as any,
      });
    }

    // 5. Warning: Subscriptions expiring in 7 days
    const sevenDaysFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
    const expiringSubs = await prisma.subscription.findMany({
      where: {
        status: 'ACTIVE',
        endDate: {
          gte: now,
          lte: sevenDaysFromNow,
        },
      },
      include: { client: true },
    });

    for (const sub of expiringSubs) {
      const client = sub.client;
      const daysLeft = Math.ceil((sub.endDate!.getTime() - now.getTime()) / (24 * 60 * 60 * 1000));
      createNotification({
        title: 'Subscription Expiring Soon',
        message: `Subscription "${sub.plan}" for ${client.company || client.name} expires in ${daysLeft} day${daysLeft === 1 ? '' : 's'}.`,
        type: 'SUBSCRIPTION_EXPIRING_SOON',
        category: 'WARNING',
        entityType: 'SUBSCRIPTION',
        entityId: sub.id,
        actionUrl: `/dashboard/subscriptions/view/${sub.id}`,
      });
    }

  } catch (error) {
    console.error('❌ [SubscriptionBilling] Error running billing cycle:', error);
  }
}

const DAY_MS = 24 * 60 * 60 * 1000;

export type ReminderKind = 'reminder' | 'overdue';

/**
 * Unpaid invoices whose next email is due: first the payment reminder
 * (due date + client's grace days), then — only once the reminder went out or
 * was skipped — the overdue notice (invoice date + client's overdue days).
 * The order matters: with the defaults the overdue date (day 10) comes before
 * the reminder date (day 19), so clients used to get "URGENT: OVERDUE" before
 * the invoice was even due.
 */
export async function findDueReminders(now = new Date()) {
  const invoices = await prisma.invoice.findMany({
    where: {
      status: { in: ['PENDING', 'OVERDUE'] },
      OR: [{ reminderSentAt: null }, { overdueSentAt: null }],
      client: { email: { not: null } },
    },
    include: { client: true, items: true },
    orderBy: { dueDate: 'asc' },
  });

  const due: { invoice: (typeof invoices)[number]; kind: ReminderKind }[] = [];
  for (const invoice of invoices) {
    const kind = nextReminderKind(invoice, invoice.client, now);
    if (kind) due.push({ invoice, kind });
  }
  return due;
}

export function nextReminderKind(
  invoice: { date: Date; dueDate: Date; reminderSentAt: Date | null; overdueSentAt: Date | null },
  client: { paymentReminderDelay: number | null; overdueNoticeDelay: number | null },
  now: Date,
): ReminderKind | null {
  if (!invoice.reminderSentAt) {
    const graceDays = client.paymentReminderDelay ?? 5;
    return now.getTime() >= invoice.dueDate.getTime() + graceDays * DAY_MS ? 'reminder' : null;
  }
  if (!invoice.overdueSentAt) {
    const overdueDays = client.overdueNoticeDelay ?? 10;
    return now.getTime() >= invoice.date.getTime() + overdueDays * DAY_MS ? 'overdue' : null;
  }
  return null;
}

type DueReminder = Awaited<ReturnType<typeof findDueReminders>>[number];

/** Mark a due email as handled without sending it. */
export async function skipDueReminder({ invoice, kind }: DueReminder, now = new Date()): Promise<void> {
  await prisma.invoice.update({
    where: { id: invoice.id },
    data: kind === 'reminder' ? { reminderSentAt: now } : { overdueSentAt: now },
  });
}

export async function sendDueReminder({ invoice: inv, kind }: DueReminder, now = new Date()): Promise<boolean> {
  const client = inv.client;
  if (!client.email) return false;

  const settings = await prisma.agencySettings.findFirst({ select: { currency: true } });
  const currencySymbol = settings?.currency ?? 'USD';
  const appUrl = process.env.FRONTEND_URL || 'http://localhost:5173';
  const amountFormatted = formatCents(inv.amount, currencySymbol);

  if (kind === 'reminder') {
    console.log(`Sending payment reminder for invoice ${inv.invoiceNumber} to ${client.email}`);
    const dueDateFormatted = inv.dueDate.toISOString().split('T')[0];
    const subject = `Payment Reminder: Invoice ${inv.invoiceNumber} is Unpaid`;
    const contentHtml = `
          <h2 style="color: #334155; font-size: 20px; margin-bottom: 16px;">Hello ${client.name},</h2>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            This is a friendly reminder that invoice <strong>${inv.invoiceNumber}</strong>, which was due on <strong>${dueDateFormatted}</strong>, is still awaiting payment.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            <strong>Amount Due:</strong> ${amountFormatted}<br/>
            <strong>Subscription Plan:</strong> ${inv.items?.[0]?.description || 'Monthly Subscription'}
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            Please log in to your portal to make the payment or arrange a bank transfer at your earliest convenience.
          </p>
        `;
    const emailHtml = await generateEmailHtml({
      title: subject,
      preheader: `Friendly reminder that invoice ${inv.invoiceNumber} is unpaid.`,
      contentHtml,
      actionButton: { label: 'View Invoice & Pay', url: `${appUrl}/dashboard/invoices` },
    });
    const result = await sendEmail({ to: client.email, subject, html: emailHtml });
    if (!result.success) {
      console.error(`Failed to send reminder for invoice ${inv.invoiceNumber}: ${result.error}`);
      return false;
    }
    await prisma.invoice.update({ where: { id: inv.id }, data: { reminderSentAt: now } });
    return true;
  }

  console.log(`Sending overdue notice for invoice ${inv.invoiceNumber} to ${client.email}`);
  const dateFormatted = inv.date.toISOString().split('T')[0];
  const subject = `URGENT: Invoice ${inv.invoiceNumber} is OVERDUE`;
  const contentHtml = `
          <h2 style="color: #dc2626; font-size: 20px; margin-bottom: 16px;">Dear ${client.name},</h2>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            We are writing to inform you that payment for invoice <strong>${inv.invoiceNumber}</strong>, generated on <strong>${dateFormatted}</strong>, is now significantly overdue.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6; font-weight: 600; color: #dc2626;">
            Your subscription payment of ${amountFormatted} remains unpaid.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            To prevent any disruption to your active subscription and agency services, please complete the payment immediately using the button below.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            If you have already made the payment, please disregard this notice or contact our billing team with your proof of payment.
          </p>
        `;
  const emailHtml = await generateEmailHtml({
    title: subject,
    preheader: `URGENT: Invoice ${inv.invoiceNumber} is overdue.`,
    contentHtml,
    actionButton: { label: 'Pay Now', url: `${appUrl}/dashboard/invoices` },
  });
  const result = await sendEmail({ to: client.email, subject, html: emailHtml });
  if (!result.success) {
    console.error(`Failed to send overdue notice for invoice ${inv.invoiceNumber}: ${result.error}`);
    return false;
  }
  await prisma.invoice.update({
    where: { id: inv.id },
    data: { status: 'OVERDUE', overdueSentAt: now },
  });
  createNotification({
    title: 'Invoice Overdue ⚠️',
    message: `Invoice ${inv.invoiceNumber} for ${client.company || client.name} is now overdue.`,
    type: 'INVOICE_OVERDUE_BILLING',
    category: 'ACTION_REQUIRED',
    entityType: 'INVOICE',
    entityId: inv.invoiceNumber || inv.id,
    actionUrl: `/dashboard/invoices/view/${inv.invoiceNumber || inv.id}`,
  });
  return true;
}
