import { prisma } from './prisma.js';
import { sendEmail, generateEmailHtml } from './email.js';
import { createNotification } from './notifications.js';

const INTERVAL_MS = 24 * 60 * 60 * 1000; // 24 hours

export function startSubscriptionBillingJob(): void {
  // Run once immediately on startup, then every 24 hours
  runBillingCycle();
  setInterval(runBillingCycle, INTERVAL_MS);
  console.log('🔄 [SubscriptionBilling] Daily billing job started.');
}

export async function runBillingCycle(): Promise<void> {
  console.log('🔄 [SubscriptionBilling] Running billing cycle...');
  try {
    const now = new Date();
    const currentDay = now.getDate();
    const currentYear = now.getFullYear();
    const currentMonth = now.getMonth(); // 0-indexed

    // 1. Generate Monthly Invoices for Active Subscriptions
    const activeSubscriptions = await prisma.subscription.findMany({
      where: { status: 'ACTIVE' },
      include: {
        client: true,
      },
    });

    const settings = await prisma.agencySettings.findFirst();
    const taxRate = settings?.taxRate ?? 0;
    const currencySymbol = settings?.currency ?? 'USD';
    const appUrl = process.env.FRONTEND_URL || 'http://localhost:5173';

    for (const sub of activeSubscriptions) {
      const client = sub.client;
      // If invoiceGenerationDay is null/undefined, default to 1st of the month
      const targetDay = client.invoiceGenerationDay ?? 1;

      // If today is the generation day for this client
      if (currentDay === targetDay) {
        // Check if an invoice has already been generated for this subscription in the current calendar month
        const startOfMonth = new Date(currentYear, currentMonth, 1);
        const endOfMonth = new Date(currentYear, currentMonth + 1, 0, 23, 59, 59, 999);

        const existingInvoice = await prisma.invoice.findFirst({
          where: {
            subscriptionId: sub.id,
            date: {
              gte: startOfMonth,
              lte: endOfMonth,
            },
          },
        });

        if (!existingInvoice) {
          console.log(`Generating monthly invoice for subscription ${sub.id} (Client: ${client.name})`);
          
          // Generate unique short invoice number
          let invoiceNumber = '';
          while (true) {
            const num = Math.floor(Math.random() * 9000 + 1000);
            invoiceNumber = `INV-${num}`;
            const existing = await prisma.invoice.findUnique({
              where: { invoiceNumber }
            });
            if (!existing) {
              break;
            }
          }

          // Compute amount with tax
          const subtotal = sub.amount; // in cents
          const totalAmount = subtotal + Math.round(subtotal * (taxRate / 100));

          // Set due date to 14 days from now
          const dueDate = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);

          await prisma.invoice.create({
            data: {
              invoiceNumber,
              clientId: sub.clientId,
              subscriptionId: sub.id,
              autoGenerated: true,
              amount: totalAmount,
              status: 'PENDING',
              date: now,
              dueDate,
              taxRate,
              notes: settings?.defaultInvoiceNotes || "Thank you for your business! Please make payment within 14 days.",
              items: {
                create: [
                  {
                    description: `Monthly subscription - ${sub.plan}`,
                    quantity: 1,
                    unitPrice: sub.amount,
                    position: 0,
                  },
                ],
              },
            },
          });
          createNotification({
            title: 'Auto-Invoice Generated',
            message: `Invoice ${invoiceNumber} generated for ${client.company || client.name} (${sub.plan}).`,
            type: 'INVOICE_AUTO_GENERATED',
            category: 'INFORMATION',
            entityType: 'INVOICE',
            entityId: invoiceNumber,
            actionUrl: `/dashboard/invoices/view/${invoiceNumber}`,
          });
          console.log(`Successfully generated invoice ${invoiceNumber} for client ${client.name}`);
        }
      }
    }

    // 2. Send Payment Reminders
    // Unpaid invoices that are past their due date by client's grace period (default 5 days)
    const pendingInvoicesForReminder = await prisma.invoice.findMany({
      where: {
        status: { in: ['PENDING', 'OVERDUE'] },
        reminderSentAt: null,
        client: {
          email: { not: null },
        },
      },
      include: {
        client: true,
        items: true,
      },
    });

    for (const inv of pendingInvoicesForReminder) {
      const client = inv.client;
      if (!client.email) continue;

      const graceDays = client.paymentReminderDelay ?? 5;
      const dueDateWithGrace = new Date(inv.dueDate.getTime() + graceDays * 24 * 60 * 60 * 1000);

      if (now >= dueDateWithGrace) {
        console.log(`Sending payment reminder for invoice ${inv.invoiceNumber} to ${client.email}`);
        
        const amountFormatted = `${currencySymbol} ${(inv.amount / 100).toFixed(2)}`;
        const dueDateFormatted = inv.dueDate.toISOString().split('T')[0];

        const subject = `Payment Reminder: Invoice ${inv.invoiceNumber} is Unpaid`;
        const contentHtml = `
          <h2 style="color: #334155; font-size: 20px; margin-bottom: 16px;">Hello ${client.name},</h2>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            This is a friendly reminder that invoice <strong>${inv.invoiceNumber}</strong>, which was due on <strong>${dueDateFormatted}</strong>, is still awaiting payment.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            <strong>Amount Due:</strong> ${amountFormatted}<br/>
            <strong>Subscription Plan:</strong> ${inv.items?.[0]?.description || 'Monthly Subscription'}
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            Please log in to your portal to make the payment or arrange a bank transfer at your earliest convenience.
          </p>
        `;

        const emailHtml = await generateEmailHtml({
          title: subject,
          preheader: `Friendly reminder that invoice ${inv.invoiceNumber} is unpaid.`,
          contentHtml,
          actionButton: {
            label: 'View Invoice & Pay',
            url: `${appUrl}/dashboard/invoices`, // fallback to portal invoices list
          },
        });

        const result = await sendEmail({
          to: client.email,
          subject,
          html: emailHtml,
        });

        if (result.success) {
          await prisma.invoice.update({
            where: { id: inv.id },
            data: { reminderSentAt: now },
          });
          console.log(`Successfully sent payment reminder and updated invoice ${inv.invoiceNumber}`);
        } else {
          console.error(`Failed to send reminder for invoice ${inv.invoiceNumber}: ${result.error}`);
        }
      }
    }

    // 3. Send Overdue Notices
    // Unpaid invoices that are past their generation date by client's overdue threshold (default 10 days)
    const pendingInvoicesForOverdue = await prisma.invoice.findMany({
      where: {
        status: { in: ['PENDING', 'OVERDUE'] },
        overdueSentAt: null,
        client: {
          email: { not: null },
        },
      },
      include: {
        client: true,
        items: true,
      },
    });

    for (const inv of pendingInvoicesForOverdue) {
      const client = inv.client;
      if (!client.email) continue;

      const overdueDays = client.overdueNoticeDelay ?? 10;
      const overdueDate = new Date(inv.date.getTime() + overdueDays * 24 * 60 * 60 * 1000);

      if (now >= overdueDate) {
        console.log(`Sending overdue notice for invoice ${inv.invoiceNumber} to ${client.email}`);

        const amountFormatted = `${currencySymbol} ${(inv.amount / 100).toFixed(2)}`;
        const dateFormatted = inv.date.toISOString().split('T')[0];

        const subject = `URGENT: Invoice ${inv.invoiceNumber} is OVERDUE`;
        const contentHtml = `
          <h2 style="color: #dc2626; font-size: 20px; margin-bottom: 16px;">Dear ${client.name},</h2>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            We are writing to inform you that payment for invoice <strong>${inv.invoiceNumber}</strong>, generated on <strong>${dateFormatted}</strong>, is now significantly overdue.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6; font-weight: 600; color: #dc2626;">
            Your subscription payment of ${amountFormatted} remains unpaid.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            To prevent any disruption to your active subscription and agency services, please complete the payment immediately using the button below.
          </p>
          <p style="margin: 0 0 16px; color: #475569; line-height: 1.6;">
            If you have already made the payment, please disregard this notice or contact our billing team with your proof of payment.
          </p>
        `;

        const emailHtml = await generateEmailHtml({
          title: subject,
          preheader: `URGENT: Invoice ${inv.invoiceNumber} is overdue.`,
          contentHtml,
          actionButton: {
            label: 'Pay Now',
            url: `${appUrl}/dashboard/invoices`,
          },
        });

        const result = await sendEmail({
          to: client.email,
          subject,
          html: emailHtml,
        });

        if (result.success) {
          await prisma.invoice.update({
            where: { id: inv.id },
            data: {
              status: 'OVERDUE',
              overdueSentAt: now,
            },
          });
          createNotification({
            title: 'Invoice Overdue ⚠️',
            message: `Invoice ${inv.invoiceNumber} for ${client.company || client.name} is now overdue.`,
            type: 'INVOICE_OVERDUE_BILLING',
            category: 'ACTION_REQUIRED',
            entityType: 'INVOICE',
            entityId: inv.invoiceNumber || inv.id,
            actionUrl: `/dashboard/invoices/view/${inv.invoiceNumber || inv.id}`,
          });
          console.log(`Successfully sent overdue notice and marked invoice ${inv.invoiceNumber} as OVERDUE`);
        } else {
          console.error(`Failed to send overdue notice for invoice ${inv.invoiceNumber}: ${result.error}`);
        }
      }
    }

    // 4. Warning: Invoices due in 3 days (deduplicated — only fire once per invoice)
    const threeDaysFromNow = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);
    const dueSoonInvoices = await prisma.invoice.findMany({
      where: {
        status: 'PENDING',
        dueDate: {
          gte: now,
          lte: threeDaysFromNow,
        },
        dueSoonNotifiedAt: null,
      },
      include: { client: true },
    });

    for (const inv of dueSoonInvoices) {
      const client = inv.client;
      const daysLeft = Math.ceil((inv.dueDate.getTime() - now.getTime()) / (24 * 60 * 60 * 1000));
      createNotification({
        title: 'Invoice Due Soon 🔔',
        message: `Invoice ${inv.invoiceNumber} for ${client.company || client.name} is due in ${daysLeft} day${daysLeft === 1 ? '' : 's'}.`,
        type: 'INVOICE_DUE_SOON',
        category: 'WARNING',
        entityType: 'INVOICE',
        entityId: inv.invoiceNumber || inv.id,
        actionUrl: `/dashboard/invoices/view/${inv.invoiceNumber || inv.id}`,
      });
      await prisma.invoice.update({
        where: { id: inv.id },
        data: { dueSoonNotifiedAt: now } as any,
      });
    }

    // 5. Warning: Subscriptions expiring in 7 days
    const sevenDaysFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
    const expiringSubs = await prisma.subscription.findMany({
      where: {
        status: 'ACTIVE',
        endDate: {
          gte: now,
          lte: sevenDaysFromNow,
        },
      },
      include: { client: true },
    });

    for (const sub of expiringSubs) {
      const client = sub.client;
      const daysLeft = Math.ceil((sub.endDate!.getTime() - now.getTime()) / (24 * 60 * 60 * 1000));
      createNotification({
        title: 'Subscription Expiring Soon',
        message: `Subscription "${sub.plan}" for ${client.company || client.name} expires in ${daysLeft} day${daysLeft === 1 ? '' : 's'}.`,
        type: 'SUBSCRIPTION_EXPIRING_SOON',
        category: 'WARNING',
        entityType: 'SUBSCRIPTION',
        entityId: sub.id,
        actionUrl: `/dashboard/subscriptions/view/${sub.id}`,
      });
    }

  } catch (error) {
    console.error('❌ [SubscriptionBilling] Error running billing cycle:', error);
  }
}
